#!/usr/bin/env bash
# Phase 2 (credential extraction): run the data-integrator `get-credentials`
# Juju action and write the OpenSearch endpoint + credentials to .env.
#
# Run AFTER `terraform apply` and once `juju status` shows all units active.
set -euo pipefail

MODEL="${JUJU_MODEL:-sphinx-search}"
APP="${DATA_INTEGRATOR_APP:-data-integrator}"
ENV_FILE="${ENV_FILE:-$(dirname "$0")/../.env}"

log() { printf '\033[1;34m[creds]\033[0m %s\n' "$*"; }

command -v jq >/dev/null 2>&1 || { echo "jq is required (sudo snap install jq)"; exit 1; }

log "Waiting for ${APP} to be active..."
juju wait-for application "${APP}" -m "${MODEL}" 2>/dev/null || \
    juju status -m "${MODEL}" "${APP}" --watch 5s

log "Running get-credentials on ${APP}/leader..."
# In Juju 3.6+, `juju run` waits for the result inline and returns JSON keyed
# by unit name, e.g. {"data-integrator/0":{"results":{"opensearch":{...}}}}.
RESULT=$(juju run -m "${MODEL}" "${APP}/leader" get-credentials --format json 2>/dev/null)

# Extract the opensearch credentials blob from the first unit's results.
CREDS=$(echo "${RESULT}" | jq -r '.[keys[0]].results.opensearch // empty')

if [ -z "${CREDS}" ]; then
    echo "No opensearch credentials in action result." >&2
    echo "${RESULT}" | jq . >&2
    exit 1
fi

# The opensearch field is a JSON object with endpoints, username, password, tls-ca.
HOST=$(echo "${CREDS}" | jq -r '.endpoints // empty' | head -n1)
USERNAME=$(echo "${CREDS}" | jq -r '.username // empty')
PASSWORD=$(echo "${CREDS}" | jq -r '.password // empty')

# Strip scheme/port for HOST; keep port separately.
HOST_NO_SCHEME=$(echo "${HOST}" | sed -E 's#^[a-z]+://##')
OPENSEARCH_HOST=$(echo "${HOST_NO_SCHEME}" | cut -d: -f1)
OPENSEARCH_PORT=$(echo "${HOST_NO_SCHEME}" | cut -d: -f2)
[ "${OPENSEARCH_PORT}" = "${OPENSEARCH_HOST}" ] && OPENSEARCH_PORT=9200

log "Writing ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/fetch-credentials.sh — do not commit.
OPENSEARCH_HOST=${OPENSEARCH_HOST}
OPENSEARCH_PORT=${OPENSEARCH_PORT}
OPENSEARCH_USER=${USERNAME}
OPENSEARCH_PASSWORD=${PASSWORD}
OPENSEARCH_VERIFY_CERTS=false
OPENSEARCH_INDEX=sphinx-docs
EOF
chmod 600 "${ENV_FILE}"

log "Done. Credentials written to ${ENV_FILE}."
